### ISSUE TITLE
Magnifying glass overlaps a long prompt

### ISSUE THREAD

**Issue by amqndin** [catppuccin/flow-launcher#1]
![image](https://github.com/catppuccin/flow-launcher/assets/123622161/a2425982-672f-4c73-a7b9-a976b53609e8)
on this image you can clearlyl see how the magnifying glass on the right overlaps the letter 'm'.

**Comment by sgoudham** [comment]
Hey :wave: 

As far as I know, Catppuccin just provides the colours to theme the launcher. I really don't think bugs relating to how the elements overlap would be our concern.

Can you replicate this bug using the default colourscheme by uninstalling Catppuccin? That will help us determine if it's a bug related to Catppuccin or if it's a bug related to Flow Launcher itself.

Thanks!

**Comment by uncenter** [comment]
I can't reproduce it on the default themes, something with our width or overflow settings is messing it up.

**Comment by uncenter** [comment]
I think I've found the issue. We don't provide any padding at:
https://github.com/catppuccin/flow-launcher/blob/120d96cf9c5838d315905456fbdda7dca0c48155/flow-launcher.tera#L31

On the default Windows 11 Light theme though, they have `<Setter Property="Padding" Value="0,4,66,0" />`, and I'm seeing similar values on other themes (`<Setter Property="Padding" Value="0,4,68,0" />` on the Base theme for example).
