### ISSUE TITLE
Broken on latest version

### ISSUE THREAD

**Issue by RuinTD** [catppuccin/flow-launcher#9]
Hello. This theme seems to have broken on Flow Launcher 1.19.0.
![image](https://github.com/user-attachments/assets/dde6e46c-3474-42d8-ad9c-d336b92d5127)

**Comment by LiquidMonkey** [comment]
I had the same issue just looking really quickly it seems that it relies on a theme that is no longer installed by default. I played around a bit and changing line 1 to 7 seems to pretty much fix it however i can not guarentee everything works since i do not know what happend to the theme it was using before
```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:system="clr-namespace:System;assembly=mscorlib"
    xmlns:userSettings="clr-namespace:Flow.Launcher.Infrastructure.UserSettings;assembly=Flow.Launcher.Infrastructure">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/Themes/Circle System.xaml" />
    </ResourceDictionary.MergedDictionaries>
```

**Comment by uncenter** [comment]
Discussing in https://discord.com/channels/907385605422448742/1262104866571030529 on the Catppuccin Discord server. I recently rewrote the theme to depend on their default "Bullet Light" theme (#8), but it was removed - renamed? - in https://github.com/Flow-Launcher/Flow.Launcher/pull/2735. If I'm reading this correctly we may be able to just change the path to the theme it is based on and it should function exactly the same.

**Comment by uncenter** [comment]
Hmm. I believe the Win 11 Light theme is what Bullet Light used to be, but looking at the source it now dynamically pulls in some colors. We might be able to just set some colors and not tie it to a specific theme? I'll keep looking into it.

**Comment by LiquidMonkey** [comment]
It was deleted: https://github.com/Flow-Launcher/Flow.Launcher/pull/2735/commits/c94e47bddb35fb7923c67a3843c2f0f66419be28#diff-f5933cf57f9f833ba22403b7d07570b369a49390df44fb707e804f340e4df05a

**Comment by uncenter** [comment]
> The bullet theme will be changed to system and become windows11 style. This is now the default.

It's more complicated than that. As I said I'll look more into it and try to figure out the best way forward. Would recommend conversing in the Discord channel I linked above if you are interested in helping.
